spring.application.name=backend
server.port=8090
debug=true

#H2 conection in file mode
#spring.datasource.url=jdbc:h2:file:./data/mydb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

#postgreSQL connection
spring.datasource.url=jdbc:postgresql://34.201.168.255:5432/noneim_db
spring.datasource.username=icecream
spring.datasource.password=ice
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#Use create  for development to reset the database to modify the tables
#spring.jpa.hibernate.ddl-auto=create 
# H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
